Repository torbennehmer/hacs-e3dc, pull requests merged in 2023-10, with the labels that each got.

#57 Additional powermeters
  custom_components/e3dc_rscp/coordinator.py
  custom_components/e3dc_rscp/sensor.py
  custom_components/e3dc_rscp/strings.json
Labels: enhancement

#67 Cleanup PR 57
  custom_components/e3dc_rscp/const.py
  custom_components/e3dc_rscp/coordinator.py
  custom_components/e3dc_rscp/sensor.py
  custom_components/e3dc_rscp/strings.json
  custom_components/e3dc_rscp/translations/en.json
Labels: refactoring

#71 Update pye3dc to 0.8.1
  custom_components/e3dc_rscp/manifest.json
  requirements.txt
Labels: dependencies

#72 Update pye3dc to 0.8.2
  custom_components/e3dc_rscp/manifest.json
  requirements.txt
Labels: dependencies

#74 Make redaction of private data dynamic
  custom_components/e3dc_rscp/diagnostics.py
Labels: bug
